apiVersion: v1
kind: Service
metadata:
  name: {{ include "nest-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "nest-app.name" . }}
    app.kubernetes.io/component: {{ .Values.labels.component }}
    app.kubernetes.io/part-of: {{ .Values.labels.partOf }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "nest-app.name" . }}
    app.kubernetes.io/component: {{ .Values.labels.component }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
