apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  labels:
    app: {{.Chart.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: CUSTOM_MESSAGE
              value: {{ .Values.env.CUSTOM_MESSAGE | quote }}
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{.Chart.Name}}-config
                  key: APP_MESSAGE
          resources:
{{ toYaml .Values.resources | indent 12 }}
