replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

config:
  APP_NAME: "generic-app"
  APP_ENV: "dev"
  LAYER: "default"
