replicaCount: 2

image:
  repository: my-node-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 200m
  #   memory: 256Mi

env:
  NODE_ENV: development
  CUSTOM_MESSAGE: "Hola desde ConfigMap"

config:
  appMessage: "Aplicación Node.js corriendo en Kubernetes 🚀"
