apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/component: {{ .Values.app.component }}
    app.kubernetes.io/part-of: {{ .Values.app.partOf }}
spec:
  replicas: {{ .Values.app.replicas }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
      app.kubernetes.io/component: {{ .Values.app.component }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app.name }}
        app.kubernetes.io/component: {{ .Values.app.component }}
      annotations:
        mycompany.com/config-version: "v1"
        kubectl.kubernetes.io/default-container: {{ .Values.app.name }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: Always
          command: ["nginx", "-g", "daemon off;"]
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          env:
            - name: COREPACK_HOME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-configmap
                  key: COREPACK_HOME
            - name: XDG_CACHE_HOME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-configmap
                  key: XDG_CACHE_HOME
            - name: HOME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-configmap
                  key: HOME
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
